### ISSUE TITLE
SVG to Image creating few nodes twice in Image

### ISSUE THREAD

**Issue by inampaki** [Irrelon/html-to-canvas#3]
Yesterday i.e. on 9th Oct 16 it was working fine, but today I am getting this weird issue that when trying to convert svg to Image it is creating few nodes twice.
I have attached the image from [example site](http://codepedia.info/editor-example/jquery-convert-html-to-image-example/)
![image](https://cloud.githubusercontent.com/assets/4215868/19212911/efaf9390-8d76-11e6-9e99-782b2797d4e8.png)

Here is the svg I replaced in example html:
`<svg id="svgArea" height="400px" width="580px"><title style="pointer-events:inherit">Layer 1</title><text y="36" x="183" font-family="Helvetica, Arial, sans-serif" font-size="24" stroke-dasharray="none">Adeel Warsi</text><text fill="null" stroke="#000" stroke-width="null" x="31.5" y="35" id="svg_1" font-size="24" font-family="Helvetica, Arial, sans-serif" text-anchor="start" xml:space="preserve" stroke-dasharray="none">Donor Name</text><text y="72" x="35" font-family="Helvetica, Arial, sans-serif" font-size="24" stroke-dasharray="none" stroke="null">S/O</text><text y="72" x="189" font-family="Helvetica, Arial, sans-serif" font-size="24" stroke-dasharray="none">Wasif Khan</text><image class="din_number" preserveAspectRatio="none" x="181" y="91" width="200" height="60" id="svg_2" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="data:image/svg+xml,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; version=&quot;1.1&quot; width=&quot;165&quot; height=&quot;35&quot;><rect width=&quot;165&quot; height=&quot;35&quot; x=&quot;0&quot; y=&quot;0&quot; fill=&quot;#FFFFFF&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;10&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;13&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;16&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;3&quot; height=&quot;20&quot; x=&quot;21&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;26&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;30&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;32&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;34&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;3&quot; height=&quot;20&quot; x=&quot;37&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;43&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;3&quot; height=&quot;20&quot; x=&quot;45&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;4&quot; height=&quot;20&quot; x=&quot;49&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;54&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;57&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;60&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;65&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;68&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;72&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;76&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;3&quot; height=&quot;20&quot; x=&quot;79&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;83&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;87&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;90&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;94&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;98&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;100&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;4&quot; height=&quot;20&quot; x=&quot;102&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;109&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;114&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;118&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;120&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;4&quot; height=&quot;20&quot; x=&quot;123&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;128&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;4&quot; height=&quot;20&quot; x=&quot;131&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;3&quot; height=&quot;20&quot; x=&quot;136&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;140&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;142&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;3&quot; height=&quot;20&quot; x=&quot;147&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;1&quot; height=&quot;20&quot; x=&quot;151&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><rect width=&quot;2&quot; height=&quot;20&quot; x=&quot;153&quot; y=&quot;0&quot; fill=&quot;#000000&quot; /><g transform=&quot;translate(82 0)&quot;><text y=&quot;30&quot; text-anchor=&quot;middle&quot; style=&quot;font-family: Arial; font-size: 10px;&quot; fill=&quot;#000000&quot;>=J30041600924190</text></g></svg>"></image><text fill="null" stroke="#000" stroke-width="null" x="46.5" y="130" id="svg_3" font-size="24" font-family="Helvetica, Arial, sans-serif" text-anchor="start" xml:space="preserve" stroke-dasharray="none">DIN #</text><text y="209" x="205" font-family="Helvetica, Arial, sans-serif" font-size="40" stroke-dasharray="none">A Positive</text><text fill="null" stroke="#000" stroke-width="null" x="49.5" y="213" id="svg_4" font-size="40" font-family="Helvetica, Arial, sans-serif" text-anchor="start" xml:space="preserve" stroke-dasharray="none">Group</text></svg>`

**Comment by Irrelon** [comment]
Are you sure you are using this project? The info on your link shows you using html2canvas.
